name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          base: header, community, activity
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          basic: repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_threshold: 1%
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: hal-year
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_limit: 5
          plugin_music_playlist: https://embed.music.apple.com/cn/playlist/b-b/pl.u-GgA5kamCZmdX5a2
          plugin_poopmap: yes
          plugin_poopmap_token: ${{ secrets.POOPMAP_TOKEN }}
          config_order: basic.repositories, lines, languages, gists, isocalendar, habits, poopmap, music
    
